sul-dlss/access-update-scripts

- githubLinks.js
> Add JS script for grabbing GitHub PR links

- autupdate.sh
> Send gem reports from dependency updates to Slack.

- repos/ruby
> Add access-update-scripts to access-update-scripts ruby project

- Jenkinsfile
Feel free to approve, and I can merge and kill the build before it triggers updates.
> Move timing of dependency updates to 2am

- infrastructure/ruby
It has been merged into common-accessioning.
> Remove etd-robots

- autupdate.sh
This reverts commit 27433d117cd14205071bb9f02388bc2297fbba90 now that a newer version of npm is installed.
> Revert "Don't use npm audit fix (just update)"

- autupdate.sh
It appears that `audit fix` only addresses security issues and not general updates.
> Run npm update in addition to npm audit fix

- infrastructure/ruby
it's being retired.
https://github.com/sul-dlss/dor-utils/issues/65
> Remove dor-utils

- infrastructure/ruby
> Remove editstore-updater

- .github/auto-comment.yml
- README.md
Now with moar robots! 🤖
This PR:
- adds some instructions to the README
- adds a Probot auto-commenter with some instructions for PR mergers
> Add some gentle reminders to kill unnecessary Jenkins builds

- infrastructure/ruby
Closes https://github.com/sul-dlss/technical-metadata-service/issues/20
> Adds technical-metadata-service repo

- infrastructure/ruby
fixing this probem:
```
remote: This repository moved. Please use the new location:        
remote:   git@github.com:sul-dlss/suri-rails.git        
remote: 
remote: Create a pull request for 'update-dependencies' on GitHub by visiting:        
remote:      https://github.com/sul-dlss/suri-rails/pull/new/update-dependencies        
```
> infrastructure: it's suri-rails not suri_rails

- merge-all.rb
* message for found branches
* count of PRs to be merged
* tolerate 404 when looking up branch protection info, since we just warn about it being off anyway (got 404 for sinopia_editor)
these helped when i was using the merge-all script this evening
> handle LD4P JS repos by default, other touchups

- infrastructure/ruby
> Add H2 (happy-heron) to Infrastructure ruby projects

- autupdate.sh
Hi, @sul-dlss/access-team folks! I welcome your feedback on this approach to keeping yarn deps in Rubyland up to date. (Draft for now.) cc: @jcoyne 
Fixes #127 (assuming that's scoped for Ruby/Rails projects, not for replacing npm in JS projects)
> Upgrade yarn dependendencies for Ruby/Rails projects

- merge-all.rb
The script currently fails to see checks that do not use the statuses API, e.g., TravisCI.com, and is/was subsequently merging PRs failing CI. This should fix that.
Note: I was not able to test this against lots of repos, so I will work with the FR next week to make sure this works properly with repos that DO NOT use checks. cc: @justinlittman
> Use checks API in addition to statuses API to determine PR CI status

- Jenkinsfile
- autupdate.sh
> Run dependency updates with ruby 2.7

- access/projects
https://purl.stanford.edu/preview
> Remove deprecated mods_display_app as its now integrated into purl and also add mise

- merge-all.rb
**CANCEL BUILD on jenkins  IF MERGING!**
> merge-all tweaks for rubocop

- infrastructure/projects.yml
Remember to kill unnecessary builds after merging: https://sul-ci-prod.stanford.edu/job/SUL-DLSS/job/access-update-scripts/job/master/ ➡️ Build History ➡️ Cancel build button (🆇)
> Remove hydrus

- .github/pull_request_template.md
> PR template:  Include link to jenkins build

- cocina_level2_prs.rb
> Print the PR url without showing \n

- access/projects.yml
> Rename POD org

- access/projects.yml
> Remove mirador_sul

- infrastructure/projects.yml
> Add infrastructure gems to list of projects needing update PRs

- Jenkinsfile
> Run access update scripts with ruby 3.0.3 for infra team.

- Jenkinsfile
> `bundle install` access + libsys dependencies with ruby 3.1

- access/projects.yml
> Remove deprecated bassi_veratti project

- infrastructure/projects.yml
> Add was-pywb to Infrastructure CI projects list

- autupdate.sh
**NOTE**: This is on hold until we get @sul-dlss/access-team feedback on these changes which are intended to 1) allow bumping of Infra CircleCI configs, and 2) allow only partial update PRs to be created. More context is in comments below.
> Update CircleCI config with latest ruby-rails orb

- access/projects.yml
> Add nta-arclight

- infrastructure/projects.yml
To keep its dependencies up to date.
> Add Globus client to Infrastructure projects list

- access/projects.yml
> Update nta-arclight to vt-arclight

- infrastructure/projects.yml
Add new folio_client gem to project list to keep dependencies up to date
> add folio_client gem to project list

- Gemfile.lock
- Jenkinsfile
- repos_wanting_update.rb
And fix removed `File.exists?` from repos_wanting_update.rb
> Update bundler version in project lock file

- infrastructure/projects.yml
> add dlme-aiflow to infra repos

- infrastructure/projects.yml
Fixes sul-dlss/orcid_client#2
Fixes sul-dlss/mais_orcid_client#3
This commit adds some new repos to Infra team weekly updates.
> Add ORCID-related client gems to Infra portfolio

- cocina_level2_prs.rb
> cocina_level2_prs: updated expected push message

- access/projects.yml
> Add sdr-metrics-api to access projects

- access/projects.yml
> Rename searchworks-status and alphabetize

- infrastructure/projects.yml
> [HOLD] Set dor_indexing gem to not cocina level 2

- .github/pull_request_template.md
- Jenkinsfile
> Update branch name to main

- Jenkinsfile
> Bump to Ruby 3.3.1 for Infra updates

- Jenkinsfile
> Run access projects with ruby 3.2.2

- infrastructure/projects.yml
Please kill the build as warned below when merging (or approve and I can do so).
> Add new h3 repo

- Jenkinsfile
> [HOLD] Use Ruby 3.4.1 for Infra builds

- Jenkinsfile
- git_hub_links.rb
> Add ability to display terser repo update messages in Slack

- infrastructure/projects.yml
closes https://github.com/sul-dlss/rialto-airflow/issues/132
> add rialto-airflow to infra dep updates

- autupdate.sh
> Update bundler as part of weekly dependency updates

- infrastructure/projects.yml
> Add wasapi_client to dependency updates
