autupdate.sh

The version of npm running on our jenkins server doesn't support `audit`
Feel free to approve, and I can merge and kill the build before it triggers updates.

Don't use npm audit fix (just update)

---

infrastructure/ruby

They have been merged into common-accessioning

Drop goobi-robot and assembly from the list

---

infrastructure/ruby

NOTE to whomever merges:  "when you merge PRs to access-update-scripts, please kill the build on (https:// )   sul-ci-prod.stanford.edu to avoid running updates again and again and again"

add was-registrar-app to infrastructure

---

infrastructure/ruby

lyberservices-scripts is a replacement for pre-assembly v3-legacy branch.

add lyberservices-scripts to infrastructure projects

---

infrastructure/ruby

This application is not maintained by the infrastructure team directly and updates may introduce breaking changes that affect the DLME managers workflow.

Remove dlme-harvest

---

infrastructure/ruby

Remove dor-fetcher-service from updates

---

infrastructure/ruby

Adds Infrastructure Integration tests for weekly dependencies updates. Replaces manual update (for example PR https://github.com/sul-dlss/infrastructure-integration-test/pull/25)

Added integration tests repo

---

access/ruby
infrastructure/ruby

As agreed, when this access work cycle started, DLME is to be moved to the access list.

Move DLME webapp to the access team updates

---

infrastructure/ruby

We will no longer need to maintain updates on rialto soon. When we've turned off the AWS infrastructure, remove rialto from automated update scripts.

Remove rialto from dep updates

---

infrastructure/ruby

Remove lyberservices-scripts from dependency updates

---

infrastructure/ruby

see https://github.com/sul-dlss/was-thumbnail-service/issues/211
maybe this is premature since the VM has yet to be destroyed, and the project yet to be moved to the deprecated org?

was-thumbnail-service has been decommissioned

---

autupdate.sh

Connects to sul-dlss/happy-heron#231
Do this in favor of hard-coding the default branch (which makes it harder to
gradually change default branches across projects).

Use each repo's configured default branch

---

merge-all.rb

Not sure why we needed all that jazz before. We took a file, wrapped it in an array just to map it?, and then flattened it for reasons that escape me, and sorted it (for reasons).

Simplify repos file reading in merge-all

---

infrastructure/projects

though it's primarily a java project, it does have `Gemfile` and `Gemfile.lock`, since capistrano is used for deployment.
fwiw, i don't think wasapi-downloader needs to be deployed for weekly dep updates, since the deployment mechanism itself is the only thing that'll be updated (since we don't yet automate dep updates for our handful of java projects).
may not be worth including in the list, and would not be bothered if this was closed accordingly -- didn't take long to make the change, and was quicker to do this only to have it closed, than to ask about it in slack.
https://github.com/sul-dlss/wasapi-downloader/blob/master/Gemfile

add wasapi-downloader to infra ruby project list

---

infrastructure/projects.yml

Now that that project has a Gemfile, we should automate keeping it up to date.

Add sdr-deploy to infrastructure projects

---

cocina_level2_prs.rb
merge-all.rb

**CANCEL [BUILD on jenkins](https://sul-ci-prod.stanford.edu/job/SUL-DLSS/job/access-update-scripts/job/master/) IF MERGING!**
This change allows `merge-all` script to be used as it has been, but adds the ability for it to be used for cocina-level2-update branches.
Step 6b of sul-dlss/cocina-models/issues/176
NOTE:  I manually made some bogus branches and PRs and tested that the selection of correct PRs worked for both "update-depenedencies" and for "cocina-level2-updates"

merge-all script can also be used for cocina-level2-update branches

---

.github/auto-comment.yml
.github/pull_request_template.md

Hopefully this will reduce the number of times we accidentally trigger dependency update PRs.
There is `auto_comment.yml` that used to work, but rather than debug that, I thought we could try this approach.

add pull request template

---

infrastructure/projects.yml

Remove the ksr-app from the infra team (no longer using the VM to run the website, using a google site instead). 

remove ksr app from infra team

---

Jenkinsfile

Drafted so no one accidentally merges it w/o killing the build. Will merge and kill the build myself once approved.
This version of ruby is already installed on the CI server and soon all Infra projects will use 3.2.
-------

Use Ruby 3.2.2 for infra builds

---

infrastructure/projects.yml

we are no longer using this app.   If we end up using it, we can re-add it.

infra project: remove dataloading-management

---

autupdate.sh

So we avoid busted dep update PRs like https://github.com/sul-dlss/google-books/pull/924#issuecomment-1568633762

Skip CircleCI CLI update check when running CI

---

infrastructure/projects.yml
merge-all.rb

Does two things:
1. adds a new infra rialto-orgs repo so we can get dependency-updates PR
2. adds a new param that can be added to the projects.yml file for infra projects so that repos can be skipped when running merge-all (and do this for new rialto-orgs repo added)

add rialto-orgs app to dependency-updates

---

cocina_level2_prs.rb

i tested in IRB:
```
irb(main):001:0> BRANCH_NAME = 'cocina-level2-updates'
=> "cocina-level2-updates"
irb(main):002:1* EXPECTED_PUSH_MESSAGES = [
irb(main):003:1*   "Branch '#{BRANCH_NAME}' set up to track remote branch '#{BRANCH_NAME}' from 'origin'",
irb(main):004:1*   "branch '#{BRANCH_NAME}' set up to track 'origin/#{BRANCH_NAME}'."
irb(main):005:0> ]
=> 
["Branch 'cocina-level2-updates' set up to track remote branch 'cocina-level2-updates' from 'origin'",
...
irb(main):006:0" result = "To github.com:sul-dlss/folio_client.git
irb(main):007:0"  * [new branch]      foo -> foo
irb(main):008:0> Branch 'foo' set up to track remote branch 'foo' from 'origin'."
=> "To github.com:sul-dlss/folio_client.git\n * [new branch]      foo -> foo\nBranch 'foo' set up to track remote branch... …
```

cocina_level2_prs: tolerate multiple possible success messages when detecting whether to create the PR

---

git_hub_links.rb

Something broke the rendering of the weekly dependency update Slack message between January 15th (when it rendered as expected) and January 22nd (when the backticks started failing to render as monospace/code). The unexpected rendering continued on January 29th. (Wrinkle: this unexpected rendering only affected the Infrastructure projects, not the Access ones. :shrug:)
You can see the literal backticks coming through above instead of rendering the text as code.
None of [the commits that landed in `access-update-scripts` during this seven-day span](https://github.com/sul-dlss/access-update-scripts/commits/master/) look obviously related to this change in behavior---but if a reviewer sees an obvious bug, holler at me and I'll be happy to make a more direct fix.
The change made here: make …

Fix output of GH links sent via Slack

---

infrastructure/projects.yml

Please be sure to kill the build as described below when merging. 

Allow rialto-orgs to be auto-merged

---

infrastructure/projects.yml

it's a python project, but the update hook was already added in https://github.com/sul-dlss/speech-to-text/pull/81
closes sul-dlss/speech-to-text#65 (i think?)

add speech-to-text service to weekly dependency updates

---

git_hub_links.rb

Currently, we get a bunch of broken Markdown.
NOTE: drafted to make sure I can control when the PR gets merged, so I can kill the Jenkins build.

Simplify terse formatting of GitHub links sent to Slack

---

merge-all.rb

This is a small change that I found very useful recently when working through a big batch of PRs for a specific change and all branches were named equally.

Allow setting BRANCH_NAME via env

---

autupdate.sh

This is needed by the sul-dlss/speech-to-text project.

Allow projects that *only* use preupdate to commit and push
